[package]
name = "pipeline-utils-rs"
version = "0.2.1"
edition = "2021"

[dependencies]
bio = "2.0.3"
serde = { version = "1.0.210", features = ["derive"] }
clap = { version = "4.5.18", features = ["derive"] }
serde_json = "1.0.128"
log = "0.4.22"
simple_logger = "5.0.0"
anyhow = "1.0.89"
colored = "2.1.0"
nalgebra = "0.33.2"
phf = { version = "0.11", features = ["macros"] }